### ISSUE TITLE
Could you please post a method that converts the models to pytorch lite for mobile?

### ISSUE THREAD

**Issue by spinoza1791** [igreat/fast-style-transfer#3]

**Comment by igreat** [comment]
I've never really worked with PyTorch mobile, but it seems to code to turn a regular model into one that's optimized for mobile is pretty simple:
```python
from torch.utils.mobile_optimizer import optimize_for_mobile

# set up the model
model = transformation_models.TransformationModel().to("cpu")

# here assuming the model was saved on a checkpoint like in this repo
checkpoint = torch.load(model_path, map_location="cpu")
model.load_state_dict(checkpoint["model_state_dict"]) 

# dummy input with the same shape as your model's input
dummy_input = torch.randn(1, 3, 224, 224)

# trace and optimize
traced_script_module = torch.jit.trace(model, dummy_input)
traced_script_module_optimized = optimize_for_mobile(traced_script_module)

traced_script_module_optimized._save_for_lite_interpreter("mobile_model.ptl")
```

Like I said I never worked with mobile app development or PyTorch mobile, but according to the documentation this saved model should just run when integrated in a mobile app (Android or iOS). You can check the [docs](https://pytorch.org/mobile/home/) to learn exactly how this can be done.

**Comment by spinoza1791** [comment]
Unfortunately, its not as easy as the docs imply. The model shape must contain all the types of parameters and layers as the original, and not simply a (1, 3, 224, 224). Like can only be remodeled with like.
